### ISSUE TITLE
Consider Removing binpacking Dep

### ISSUE THREAD

**Issue by jonathandelgado** [twolfson/layout#6]
`binpacking` has an issue with module exports. - https://github.com/jsmarkus/node-bin-packing/issues/3

This makes running spritesmith (or layout) in an environment like atom/node-webkit impossible.

The current version is three years old with no active maintainer, would you consider forking the corresponding btree code and crediting the author in this repo?

I'd be more than happy to throw in a PR if you are willing to merge.

**Comment by twolfson** [comment]
I would prefer to avoid forking since it is one more repo to the noise in `npm` and I have a feeling that package would be a pain to maintain. We added the `binary-tree` algorithm 2 years ago so there are probably other `bin-packing` modules out by now.

https://github.com/twolfson/layout/commit/b48cf68341210d37864ba5b83a64e28df27d4c2f#diff-06fce7273454b9fb06fcc03727810a77

A quick search found:

https://github.com/munro/boxpack

https://github.com/shama/atlaspack

I think `boxpack` looks like it has a very similar interface. Want to take a shot at replacing that?

**Comment by jonathandelgado** [comment]
@twolfson Good call, didn't event think about alternative packages.

I'm looking into it right now.

**Comment by twolfson** [comment]
It looks like `boxpack` isn't as efficient as `binpacking` =/

https://github.com/Ensighten/spritesmith/issues/48

Going to setup a test to verify we are as small on `binpacking` for the algorithm. It could be we are missing a switch on `boxpack` or need to check out another module.

**Comment by twolfson** [comment]
Dived into the code of each one. `boxpack` packed based on `x`/`y` distance from `(0,0)` not on best fit in empty spaces. `bin-packing` compares widths and chooses best choice.

I am going to look for another alternative module. Otherwise, we will prob be forking `bin-packing`.

**Comment by twolfson** [comment]
After more research, I have found:

https://github.com/bryanburgers/bin-pack

which is a `node` only flavor of `bin-packing`. I guess we are going back to what works =)

**Comment by jonathandelgado** [comment]
@twolfson Ah, sorry about that. My sheets generated the exact same. Glad you got it fixed!

**Comment by twolfson** [comment]
No worries. The tests didn't cover this edge case either =)
